### ISSUE TITLE
Graph pro manual?

### ISSUE THREAD

**Issue by H-EKE** [pegerto/graphpro#33]
Hi @pegerto ,

I would like to use graphpro but I didn't found any manual or guide when it will be available?

Thanks in advance,

Hocine

**Comment by pegerto** [comment]
Hello Hocine 

Apologies for the slow response, I have included a getting started document into the auto generated docs:

[Read the docs](https://graphpro.readthedocs.io/en/latest/)

If you have any specific issue feel free to reach me,  pegerto [at] gmail.com.

Thanks for your interest in this project.

**Comment by H-EKE** [comment]
Dear @pegerto 

Thanks a lot!
